- name: Creating Secrets
  uri:
   url: http://{{ vault_url }}/v1/{{ secret_engine_path }}/data/{{ secret_path }}
   method: POST
   body_format: json
   status_code: [200,202,204]
   return_content: true
   headers:
    Content-Type: application/json
    X-Vault-Token: "{{ token }}"
   body: "{{ lookup('file','payload.json') }}"
  register: outer


- name: Checking if secret is created
  assert:
    that:
      - outer.status == 200

    fail_msg: "Secret not created"
    success_msg: "Secret created successfully"
