- name: Secret checking and enabling   
  block:
    - name: Enabling secret engine if not already enabled
      uri:
       url: http://{{ vault_url }}/v1/sys/mounts/{{ secret_engine_path }}
       method: POST
       body_format: json
       status_code: [200,202,204]
       return_content: true
       headers:
        Content-Type: application/json
        X-Vault-Token: "{{ token }}"
       body: '{ "type": "{{ secret_type }}" , "config": { "force_no_cache": true }}'
  rescue:
    - name: status message
      debug:
       msg: 'This Engine path is already enabled'

